# environment
visible_gpus: '0'
seed: 42

# dataset
dataset: 'gbmlgg'
task: 'survival'
data_root: "/datastorage/li/TCGA_GBMLGG"
pickle_path: "./datasets/TCGA_GBMLGG/tcga_gbmlgg.pkl"
checkpoints: './checkpoints'
results: './results'

kfold: 5
stratify: True
step: 30. # step for time bin discretization in days
normalize: False

# model
method: 'ordsurv' # 'ordsurv', 'deephit', 'deepsurv', 'discrete', 'angularord', 'ordsoftmax'
backbone: 'resnet18'
patch_size: 16
pretrained: True


# training
workers: 0
optimizer: 'Adam'
epochs: 50
batch_size: 512
lr: 2.0e-4
lr_policy: 'cosine'
weight_decay: 0.01
verbose: True
